language: csharp
os:
  - linux
mono: none
dotnet: 3.1
sudo: required
script:
  # build and run unit + integration tests + pack + publish to NuGet
  - ./build.sh -t TravisCI --nugetApiKey=$nugetApiKey
services:
  - docker